name: Production Multi-Platform Publish

on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*[+]*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant Execute Permissions to Gradlew
        run: chmod +x gradlew

      - name: Build and Deploy to Endpoints
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_SECRET }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_SECRET }}
        run: ./gradlew publishMod -Prelease_type=release
